language: node_js
node_js:
- 12

script:
- eslint 'src/**'
- npm run test:coveralls

deploy:
  provider: heroku
  api_key:
    secure: sT5D6LImRp9t5P1zHzogpjrlUDr/JqtlE5Lze/e1tLpxONyPyfFoF++LKWSbvw+myLC1S0/7x0NqHYT7BbDx5lmNrR2m7pKiNWd0rkQ4mdLLnGeG04JpMtcnVtg2lcML2Z74dY8vwRJiPBC8A3AI/k4KOD1pQRb1JTdnnlpxBx/j9OIqogbVfanj+n8RHzl/s1R5Ou2JA7c7scvwxhhrfphOFJv7eesSbv4M/+kXFwQJWyIpsybUK48C9NPJXoIrlKV1VwRlntHQvrPqDl9k7nqjuQVVW9XZR9uZ96Gqem94KOQcdJz0csi+MMtgwSALmtonCcCBmA5zrkrd7LgUjeflS+0VxXOZ6GM3oTG5AHuxBH6DJuzsUXh8vEfxKlzp5f0CQXVvfaWXOhEjsEGNGbrsK12F0USUQct/nnSonu554v9eRe8ShDHUgpdYCvQF+jUpDiyDEhmkwEHAy6We3V55sf8du6xCAwnQrQLDDjmRKZjsHsYcf5wfn7M04oGeaPyqov8k78Vk+X6i0vZLZK8HbpwYzs6lxaKH3qYGpSv8IeP42BZUGs1q+OCtkCGq1odSW2O1MPCbdkBm5feYZ8VMfk244vRkCGjjpmbG+T5SfdXxceOEDpg7+ITxtklx9rK7SkiImIwn5xWYHxfvVH4RZzZLI4KwT5jsiUptnfw=
  on: main
